2022/08/18 19:35:16 [error] 9#9: *13 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://192.168.128.5:9000", host: "vk.test.ru"
2022/08/18 19:36:35 [error] 9#9: *13 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://192.168.128.5:9000", host: "vk.test.ru"
2022/08/18 19:41:18 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://192.168.128.5:9000", host: "vk.test.ru"
2022/08/18 19:44:25 [crit] 7#7: *5 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 192.168.128.1, server: 0.0.0.0:443
2022/08/18 19:44:25 [crit] 7#7: *6 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 192.168.128.1, server: 0.0.0.0:443
2022/08/18 19:44:31 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://192.168.128.5:9000", host: "vk.test.ru"
2022/08/18 19:45:03 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://192.168.128.5:9000", host: "vk.test.ru"
2022/08/18 19:49:20 [error] 8#8: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.128.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://192.168.128.5:9000", host: "vk.test.ru"
2022/08/18 19:49:21 [error] 8#8: *3 FastCGI sent in stderr: "PHP message: [critical] Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Error: Maximum execution time of 30 seconds exceeded" at /vk/vendor/symfony/error-handler/DebugClassLoader.php line 1135" while reading upstream, client: 192.168.128.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://192.168.128.5:9000", host: "vk.test.ru"
2022/08/18 19:51:23 [error] 8#8: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://vk.test.ru/"" at /vk/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128" while reading response header from upstream, client: 192.168.128.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://192.168.128.5:9000", host: "vk.test.ru"
2022/08/21 06:31:39 [error] 7#7: *15 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:31:39 [error] 7#7: *15 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: 2022-08-21T09:31:39+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/vk/var/log)" while reading upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:31:58 [error] 7#7: *15 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:31:58 [error] 7#7: *15 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: 2022-08-21T09:31:58+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/vk/var/log)" while reading upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:33:11 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:33:11 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: 2022-08-21T09:33:11+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/vk/var/log)" while reading upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:39:17 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:39:17 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: 2022-08-21T09:39:17+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/vk/var/log)" while reading upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:49:34 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://vk/"" at /vk/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128" while reading response header from upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:49:35 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://vk/favicon.ico" (from "https://vk/")" at /vk/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128" while reading response header from upstream, client: 172.18.0.1, server: vk, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk", referrer: "https://vk/"
2022/08/21 06:53:38 [crit] 7#7: *5 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:443
2022/08/21 06:53:38 [crit] 7#7: *6 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:443
2022/08/21 06:53:38 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://vk/"" at /vk/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128" while reading response header from upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:53:57 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://vk/"" at /vk/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128" while reading response header from upstream, client: 172.18.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "vk"
2022/08/21 06:57:45 [crit] 7#7: *2 realpath() "/vk/public" failed (2: No such file or directory), client: 172.19.0.1, server: vk, request: "GET / HTTP/2.0", host: "vk"
2022/08/21 06:57:45 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "vk"
2022/09/12 18:03:41 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk"
2022/09/12 18:03:42 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk", referrer: "https://vk/"
2022/09/12 18:03:44 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk"
2022/09/12 18:03:44 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk", referrer: "https://vk/"
2022/09/12 18:23:15 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk"
2022/09/12 18:23:16 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk", referrer: "https://vk/"
2022/09/12 18:23:21 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk"
2022/09/12 18:23:22 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk", referrer: "https://vk/"
2022/09/12 18:23:50 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk"
2022/09/12 18:23:51 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk", referrer: "https://vk/"
2022/09/12 18:25:14 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk"
2022/09/12 18:25:15 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: vk, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.21.0.6:9002", host: "vk", referrer: "https://vk/"
2022/09/12 19:59:56 [error] 7#7: *6 FastCGI sent in stderr: "PHP message: 2022-09-12T22:59:56+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:01:14 [error] 7#7: *6 FastCGI sent in stderr: "PHP message: 2022-09-12T23:01:14+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:02:20 [error] 7#7: *6 FastCGI sent in stderr: "PHP message: 2022-09-12T23:02:20+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:02:23 [error] 7#7: *6 FastCGI sent in stderr: "PHP message: 2022-09-12T23:02:23+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
2022/09/12 20:07:08 [error] 7#7: *17 FastCGI sent in stderr: "PHP message: 2022-09-12T23:07:08+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/symfony/var/log)" while reading upstream, client: 172.21.0.1, server: symfony, request: "GET / HTTP/2.0", upstream: "fastcgi://172.21.0.11:9000", host: "symfony"
